  name: mon_app
  description: "A new Flutter project."
  publish_to: 'none'

  version: 1.0.0+1

  environment:
    sdk: ^3.9.2

  dependencies:
    flutter:
      sdk: flutter
    cupertino_icons: ^1.0.8
    google_fonts: ^6.1.0
    audioplayers: ^6.5.1
    just_audio: ^0.10.5
    provider: ^6.1.2
  dev_dependencies:
    flutter_test:
      sdk: flutter
    flutter_lints: ^6.0.0

  flutter:
    uses-material-design: true

    assets:
      - assets/images/
      #- assets/icons/
      #- assets/videos/
      - assets/audio/bretagne.mp3
      - assets/audio/Commencer.m4a
      - assets/audio/bretagne_access.m4a
      - assets/audio/Texte agrandi activé.m4a
      - assets/audio/texte agrandi désactivé.m4a
      - assets/audio/all_scénario.mp3
      - assets/audio/Contraste activé.m4a
      - assets/audio/Contraste désactivé.m4a
      - assets/audio/Inventaire.m4a
      - assets/audio/Mode daltonien activé.m4a
      - assets/audio/Mode daltonien désactivé.m4a
      - assets/audio/Narration activé.m4a
      - assets/audio/Narration désactivé.m4a
      - assets/audio/Passer enigme.m4a
      - assets/audio/Retour.m4a
      - assets/audio/son activé.m4a
      - assets/audio/son désactivé.m4a
      - assets/audio/Sortir de la cabane.m4a
      - assets/audio/Valider.m4a
      - assets/audio/Accueil.m4a
      - assets/audio/Accessibilité.m4a
      - assets/audio/Reinitialiser.m4a
      - assets/audio/cabane_reveil.m4a
      - assets/audio/porte en bois.m4a
